[package]
name = "modernweb-booth-question"
version = "0.1.0"
authors = ["Tzu-Yin Hong <lili668668@gmail.com>"]
edition = "2018"

[dependencies]
termion = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
